{%- macro generate_schema_name(custom_schema_name, node) -%}
    {%- set default_schema = target.schema | trim -%}  {# e.g. dbt_cloud_pr_123_456 #}
    {%- set custom = custom_schema_name | trim if custom_schema_name else '' -%}
    {%- set is_ci = env_var('DBT_ENVIRONMENT') == 'ci' -%}

    {%- if is_ci -%}
        {# In CI: keep the schema name generated by dbt Cloud (must start with dbt_cloud_pr_) 
           and optionally append the custom schema as a suffix #}
        {%- if custom -%}
            {{ default_schema ~ '_' ~ custom }}
        {%- else -%}
            {{ default_schema }}
        {%- endif -%}
    {%- else -%}
        {# In non-CI environments: use the custom schema if provided; otherwise fall back to target.schema #}
        {%- if custom -%}
            {{ custom }}
        {%- else -%}
            {{ default_schema }}
        {%- endif -%}
    {%- endif -%}
{%- endmacro -%}